sh validate.sh ../xsdrt/maindoc/UBL-TransportationStatus-2.1.xsd ../xml/MyTransportationStatus.xml
sh validate.sh ../xsdrt/maindoc/UBL-CreditNote-2.1.xsd ../xml/UBL-CreditNote-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-CreditNote-2.1.xsd ../xml/UBL-CreditNote-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-DebitNote-2.1.xsd ../xml/UBL-DebitNote-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-DespatchAdvice-2.1.xsd ../xml/UBL-DespatchAdvice-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ExceptionCriteria-2.1.xsd ../xml/UBL-ExceptionCriteria-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ExceptionNotification-2.1.xsd ../xml/UBL-ExceptionNotification-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Forecast-2.1.xsd ../xml/UBL-Forecast-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ForecastRevision-2.1.xsd ../xml/UBL-ForecastRevision-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ForwardingInstructions-2.1.xsd ../xml/UBL-ForwardingInstructions-2.0-Example-International.xml
sh validate.sh ../xsdrt/maindoc/UBL-FreightInvoice-2.1.xsd ../xml/UBL-FreightInvoice-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-FulfilmentCancellation-2.1.xsd ../xml/UBL-FulfilmentCancellation-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-GoodsItemItinerary-2.1.xsd ../xml/UBL-GoodsItemItinerary-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-InstructionForReturns-2.1.xsd ../xml/UBL-InstructionForReturns-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-InventoryReport-2.1.xsd ../xml/UBL-InventoryReport-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Detached.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Enveloped.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Example-NS1.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Example-NS2.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Example-NS3.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Example-NS4.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.1-Example-Trivial.xml
sh validate.sh ../xsdrt/maindoc/UBL-Invoice-2.1.xsd ../xml/UBL-Invoice-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Order-2.1.xsd ../xml/UBL-Order-2.0-Example-International.xml
sh validate.sh ../xsdrt/maindoc/UBL-Order-2.1.xsd ../xml/UBL-Order-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Order-2.1.xsd ../xml/UBL-Order-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-OrderCancellation-2.1.xsd ../xml/UBL-OrderCancellation-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-OrderChange-2.1.xsd ../xml/UBL-OrderChange-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-OrderResponse-2.1.xsd ../xml/UBL-OrderResponse-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-OrderResponseSimple-2.1.xsd ../xml/UBL-OrderResponseSimple-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-OrderResponseSimple-2.1.xsd ../xml/UBL-OrderResponseSimple-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ProductActivity-2.1.xsd ../xml/UBL-ProductActivity-2.1-Example-1.xml
sh validate.sh ../xsdrt/maindoc/UBL-ProductActivity-2.1.xsd ../xml/UBL-ProductActivity-2.1-Example-2.xml
sh validate.sh ../xsdrt/maindoc/UBL-ProductActivity-2.1.xsd ../xml/UBL-ProductActivity-2.1-Example-3.xml
sh validate.sh ../xsdrt/maindoc/UBL-Quotation-2.1.xsd ../xml/UBL-Quotation-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Quotation-2.1.xsd ../xml/UBL-Quotation-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-ReceiptAdvice-2.1.xsd ../xml/UBL-ReceiptAdvice-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Reminder-2.1.xsd ../xml/UBL-Reminder-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-RemittanceAdvice-2.1.xsd ../xml/UBL-RemittanceAdvice-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-RequestForQuotation-2.1.xsd ../xml/UBL-RequestForQuotation-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-RequestForQuotation-2.1.xsd ../xml/UBL-RequestForQuotation-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-RetailEvent-2.1.xsd ../xml/UBL-RetailEvent-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-SelfBilledCreditNote-2.1.xsd ../xml/UBL-SelfBilledCreditNote-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Statement-2.1.xsd ../xml/UBL-Statement-2.0-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-StockAvailabilityReport-2.1.xsd ../xml/UBL-StockAvailabilityReport-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TradeItemLocationProfile-2.1.xsd ../xml/UBL-TradeItemLocationProfile-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportExecutionPlan-2.1.xsd ../xml/UBL-TransportExecutionPlan-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportExecutionPlanRequest-2.1.xsd ../xml/UBL-TransportExecutionPlanRequest-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportProgressStatus-2.1.xsd ../xml/UBL-TransportProgressStatus-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportProgressStatusRequest-2.1.xsd ../xml/UBL-TransportProgressStatusRequest-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportServiceDescription-2.1.xsd ../xml/UBL-TransportServiceDescription-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportServiceDescriptionRequest-2.1.xsd ../xml/UBL-TransportServiceDescriptionRequest-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportationStatus-2.1.xsd ../xml/UBL-TransportationStatus-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-TransportationStatusRequest-2.1.xsd ../xml/UBL-TransportationStatusRequest-2.1-Example.xml
sh validate.sh ../xsdrt/maindoc/UBL-Waybill-2.1.xsd ../xml/UBL-Waybill-2.0-Example-International.xml
